project_id = "cgpgyatxmhdpenzstzcu"

[functions.send-telegram]
verify_jwt = false

[functions.send-fcm]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.import-sheet-data]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false

